# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import drivesvr_pb2 as drivesvr__pb2


class DriveStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.DriveSvr = channel.unary_unary(
            '/device.Drive/DriveSvr',
            request_serializer=drivesvr__pb2.DriveSvrRequest.SerializeToString,
            response_deserializer=drivesvr__pb2.DriveSvrResponse.FromString,
            )


class DriveServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def DriveSvr(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriveServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'DriveSvr': grpc.unary_unary_rpc_method_handler(
            servicer.DriveSvr,
            request_deserializer=drivesvr__pb2.DriveSvrRequest.FromString,
            response_serializer=drivesvr__pb2.DriveSvrResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'device.Drive', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
