# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drivesvr.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drivesvr.proto',
  package='device',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0e\x64rivesvr.proto\x12\x06\x64\x65vice\"K\n\x0f\x44riveSvrRequest\x12\r\n\x05\x44\x65vid\x18\x01 \x01(\t\x12\x0b\n\x03\x43md\x18\x02 \x01(\r\x12\x0e\n\x06\x43mdStr\x18\x03 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x04 \x01(\x0c\" \n\x10\x44riveSvrResponse\x12\x0c\n\x04\x44\x61ta\x18\x01 \x01(\x0c\x32H\n\x05\x44rive\x12?\n\x08\x44riveSvr\x12\x17.device.DriveSvrRequest\x1a\x18.device.DriveSvrResponse\"\x00\x62\x06proto3')
)




_DRIVESVRREQUEST = _descriptor.Descriptor(
  name='DriveSvrRequest',
  full_name='device.DriveSvrRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Devid', full_name='device.DriveSvrRequest.Devid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Cmd', full_name='device.DriveSvrRequest.Cmd', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CmdStr', full_name='device.DriveSvrRequest.CmdStr', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Data', full_name='device.DriveSvrRequest.Data', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=101,
)


_DRIVESVRRESPONSE = _descriptor.Descriptor(
  name='DriveSvrResponse',
  full_name='device.DriveSvrResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Data', full_name='device.DriveSvrResponse.Data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=135,
)

DESCRIPTOR.message_types_by_name['DriveSvrRequest'] = _DRIVESVRREQUEST
DESCRIPTOR.message_types_by_name['DriveSvrResponse'] = _DRIVESVRRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DriveSvrRequest = _reflection.GeneratedProtocolMessageType('DriveSvrRequest', (_message.Message,), {
  'DESCRIPTOR' : _DRIVESVRREQUEST,
  '__module__' : 'drivesvr_pb2'
  # @@protoc_insertion_point(class_scope:device.DriveSvrRequest)
  })
_sym_db.RegisterMessage(DriveSvrRequest)

DriveSvrResponse = _reflection.GeneratedProtocolMessageType('DriveSvrResponse', (_message.Message,), {
  'DESCRIPTOR' : _DRIVESVRRESPONSE,
  '__module__' : 'drivesvr_pb2'
  # @@protoc_insertion_point(class_scope:device.DriveSvrResponse)
  })
_sym_db.RegisterMessage(DriveSvrResponse)



_DRIVE = _descriptor.ServiceDescriptor(
  name='Drive',
  full_name='device.Drive',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=137,
  serialized_end=209,
  methods=[
  _descriptor.MethodDescriptor(
    name='DriveSvr',
    full_name='device.Drive.DriveSvr',
    index=0,
    containing_service=None,
    input_type=_DRIVESVRREQUEST,
    output_type=_DRIVESVRRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DRIVE)

DESCRIPTOR.services_by_name['Drive'] = _DRIVE

# @@protoc_insertion_point(module_scope)
